### ISSUE TITLE
Error Checking and Data Cleaning

### ISSUE THREAD

**Issue by Carson-MD** [Carson-MD/4400#3]
Our database must be reviewed to ensure:
-No typos
-All elements from association() (gene, allele, drug, effect, group) have corresponding facts under each subheading.
-Simplify 'effects' as much as possible
-Consider splitting group into group and population

MORE DIFFICULT TASKS
-Unify alleles (some are in **'*'** form while others are in **'rs'** form, also for '*' some are in pairs while others are singles. Task would be to consult the corresponding PUBMED IDs and look to unify under a common format.
-Quantify the relationships wherever possible (requires reading the articles and looking for quantification of some sort).

**Comment by LamaKha** [comment]
Errors were corrected and data was cleaned.
